version: '3.9'

## docker-compose build --no-cache && docker-compose -p vault-svc-stack -f docker-compose.yml up -d
## docker-compose -p vault-svc-stack -f docker-compose.yml down

services:

  vault-svc:
    container_name: vault-svc
    hostname: vault-svc
    image: hashicorp/vault:latest
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 8200
    ports:
      - 8200:8200
    environment:
      VAULT_LOG_LEVEL: trace
      VAULT_ADDR: http://localhost:8200
      VAULT_API_ADDR: http://localhost:8200
      DATABASE_URL: postgres://postgres:postgres@host.docker.internal:5432/postgres
      PORT: 8200
    cap_add:
      - IPC_LOCK
    networks:
      vault-bridge:
        aliases:
          - vault-svc
    volumes:
      - vault-server-config:/vault/config/
      - vault-server-file:/vault/file
      - vault-server-logs:/vault/logs/
      - vault-server-plugins:/vault/plugins/


volumes:

  vault-server-config:
    name: vault-server-config
    driver: local

  vault-server-file:
    name: vault-server-file
    driver: local

  vault-server-logs:
    name: vault-server-logs
    driver: local

  vault-server-plugins:
    name: vault-server-plugins
    driver: local


networks:

  vault-bridge:
    name: vault-bridge
    external: false
